from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import math

from .config import ProjectConfig
from .domain import Candidate, Recommendation, SimulationResult, Snapshot, utc_now
from .fluidit.model import FHeatModel, ScenarioSpec
from .fluidit.runner import FluiditRunner


@dataclass(frozen=True)
class ScoredResult:
    result: SimulationResult
    objective: float
    feasible: bool


class ScenarioOptimizer:
    def __init__(self, config: ProjectConfig, runner: FluiditRunner):
        self.config = config
        self.runner = runner

    def optimize(self, snapshot: Snapshot, trigger: str) -> Recommendation:
        model_path = self.config.resolve("project.model")
        work_root = self.config.resolve("project.work_dir") / utc_now().strftime("run_%Y%m%dT%H%M%SZ")
        work_root.mkdir(parents=True, exist_ok=True)
        parent_uuid = str(self.config.get("fluidit.parent_scenario_uuid"))
        current_t = float(self.config.get("control.initial_supply_temperature_c", 95.0))
        current_dp = float(self.config.get("control.initial_differential_pressure_bar", 4.0))
        scored: list[ScoredResult] = []

        candidates = [
            Candidate(float(temp), float(dp))
            for temp in self.config.get("optimization.supply_temperature_candidates_c", [])
            for dp in self.config.get("optimization.differential_pressure_candidates_bar", [])
            if self._within_rate_limits(float(temp), float(dp), current_t, current_dp)
        ]
        for index, candidate in enumerate(candidates, start=1):
            candidate_dir = work_root / f"candidate_{index:02d}_{candidate.supply_temperature_c:g}C_{candidate.differential_pressure_bar:g}bar"
            candidate_dir.mkdir(parents=True, exist_ok=True)
            spec = ScenarioSpec(
                name=f"AI {trigger} {candidate.supply_temperature_c:g}C {candidate.differential_pressure_bar:g}bar",
                parent_uuid=parent_uuid,
                snapshot=snapshot,
                load_mode="combined",
                supply_temperature_c=candidate.supply_temperature_c,
                differential_pressure_bar=candidate.differential_pressure_bar,
                ambient_temperature_c=float(self.config.get("environment.ambient_temperature_c", -20.1)),
                ground_temperature_c=float(self.config.get("environment.ground_temperature_c", 10.0)),
                return_temperature_c=float(self.config.get("environment.return_temperature_c", 47.0)),
                description="Automatically generated by the Python supervisory optimizer.",
            )
            derived_model = FHeatModel(model_path, self.config).derive(
                candidate_dir / "candidate.fheat", [spec], active_uuid=spec.scenario_uuid
            )
            result = self.runner.run(
                derived_model, spec.scenario_uuid, candidate, snapshot, candidate_dir
            )
            scored.append(self._score(result, current_t, current_dp))

        feasible = [item for item in scored if item.feasible]
        if not feasible:
            return Recommendation(
                timestamp=utc_now(), trigger=trigger, candidate=None, objective=None,
                safe=False, complete_fluidit_validation=False,
                reason="No candidate satisfied convergence and engineering constraints.",
                simulations=[item.result for item in scored],
            )
        best = min(feasible, key=lambda item: item.objective)
        require_complete = bool(self.config.get("control.require_complete_fluidit_metrics", True))
        safe = best.result.complete_metrics or not require_complete
        if best.result.source == "mock_not_fluidit":
            safe = False
        reason = "Best feasible candidate selected."
        if not safe:
            reason += " Recommendation only: full real Fluidit metrics are not available."
        return Recommendation(
            timestamp=utc_now(), trigger=trigger, candidate=best.result.candidate,
            objective=best.objective, safe=safe,
            complete_fluidit_validation=best.result.complete_metrics and best.result.source != "mock_not_fluidit",
            reason=reason, simulations=[item.result for item in scored],
        )

    def _score(self, result: SimulationResult, current_t: float, current_dp: float) -> ScoredResult:
        required_dp = float(self.config.get("optimization.required_min_dp_bar", 3.5))
        maximum_deficit = float(self.config.get("optimization.maximum_deficit_kw", 0.1))
        complete = all(
            value is not None
            for value in (result.max_deficit_kw, result.min_dp_bar, result.heat_loss_kw)
        )
        feasible = bool(
            result.converged
            and complete
            and result.max_deficit_kw <= maximum_deficit
            and result.min_dp_bar >= required_dp
        )
        if not complete:
            return ScoredResult(result, math.inf, False)
        pump_energy_kwh = result.pump_energy_kwh or 0.0
        setpoint_change = (
            (result.candidate.supply_temperature_c - current_t) ** 2
            + 10.0 * (result.candidate.differential_pressure_bar - current_dp) ** 2
        )
        objective = (
            float(self.config.get("optimization.weight_pump_energy", 0.0)) * pump_energy_kwh
            + float(self.config.get("optimization.weight_heat_loss", 0.03)) * result.heat_loss_kw
            + float(self.config.get("optimization.weight_deficit", 1000.0)) * result.max_deficit_kw
            + float(self.config.get("optimization.weight_setpoint_change", 2.0)) * setpoint_change
        )
        return ScoredResult(result, objective, feasible)

    def _within_rate_limits(self, temp: float, dp: float, current_t: float, current_dp: float) -> bool:
        return (
            float(self.config.get("control.min_supply_temperature_c")) <= temp <= float(self.config.get("control.max_supply_temperature_c"))
            and float(self.config.get("control.min_differential_pressure_bar")) <= dp <= float(self.config.get("control.max_differential_pressure_bar"))
            and abs(temp - current_t) <= float(self.config.get("control.max_supply_change_per_cycle_c"))
            and abs(dp - current_dp) <= float(self.config.get("control.max_dp_change_per_cycle_bar"))
        )
